{
 "title": "Domain Expiration Overview",
 "description": "For more information, please visit https://github.com/zifter/helm-charts/tree/main/charts/domain-exporter",
 "tags": [
  "domain",
  "prometheus",
  "overview"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All domains: Expiration",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "min by (domain) (domain_expiry_days)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Overview: Will expire soon",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (domain) (30 >= domain_expiry_days )",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "SSL Cert Will expire soon",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (domain) (5 >= cert_expiry_days >= 0)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Site not opening",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (domain) (domain_site_alive != 1)",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}